import pandas as pd

def preprocess_classes():
    # Read the dataset (the file generated by your scraping script)
    input_file = "ucsc_class_data.csv"
    output_file = "ucsc_class_data_preprocessed.csv"
    
    df = pd.read_csv(input_file)
    
    # Define a function to decide whether a row should be removed
    def should_remove(row):
        location = row["Location"] if pd.notna(row["Location"]) else ""
        day_time = row["Day/Time"] if pd.notna(row["Day/Time"]) else ""
        
        loc_lower = location.lower()
        dt_lower = day_time.lower().strip()
        
        # Condition 1: Remove if the location indicates an online or remote class.
        if "online" in loc_lower or "remote instruction" in loc_lower or "digital arts" in loc_lower:
            return True
        
        # Condition 4: Remove if the location indicates a "TBD In Person" class.
        if "tbd in person" in loc_lower:
            return True
        
        # Condition 2: Remove if the day/time indicates cancellation.
        if "cancelled" in dt_lower:
            return True
        
        # Condition 3: Remove if no scheduling information is provided.
        # (e.g., the day/time string is exactly "Day and Time:")
        if dt_lower == "day and time:":
            return True
        
        return False

    # Apply the filter: keep rows that do NOT meet the removal criteria.
    df_filtered = df[~df.apply(should_remove, axis=1)]
    
    # Save the processed dataset to a new CSV file.
    df_filtered.to_csv(output_file, index=False)
    
    return df_filtered

if __name__ == "__main__":
    df_preprocessed = preprocess_classes()
    print("Preprocessing complete.")
    print("New dataset has", len(df_preprocessed), "rows.")
    print(df_preprocessed.head())
